### ISSUE TITLE
tor unavailable

### ISSUE THREAD

**Issue by danpaul** [bendiken/tor-ruby#3]
I'm not sure if you're still developing this but it doesn't seem to be working for me. Just wanted to let you know.

I'm using OSX 10.8.2, Ruby 1.9.3, and Tor 0.2.3.25.

After `gem install tor` is successful, I get the following:

```ruby
require 'rubygems'
require 'tor'

Tor.avaialble? #=> false
Tor.version.class #=> NilClass
```

**Comment by sergey-alekseev** [comment]
I get:
```
[1] pry(main)> Tor.available?
=> true
[2] pry(main)> Tor.version
=> nil
with
❯ ruby -v                                                                                                                                                                            
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]
❯ tor --version
Tor version 0.2.5.12 (git-99d0579ff5e0349f)
```

**Comment by tuckerwales** [comment]
@bendiken: I believe this issue should now be closed. I've tested the latest codebase with the latest version of Tor and everything works as expected.
![screenshot 2015-06-18 20 55 09](https://cloud.githubusercontent.com/assets/166597/8240723/9d0f1f4a-15fc-11e5-8cec-a381e7bc6816.png)

**Comment by bendiken** [comment]
Thanks, @tuckerwales!
